apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx  #linha 15
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3006
      nodePort: 30001
